// Style Dictionary configuration.
//
// Style Dictionary reads the design tokens in tokens/ and generates
// platform files from them. Today it produces one file: CSS variables at
// build/css/tokens.css.
//
// Build it with:  npm run tokens

export default {
  // Where the source tokens live. "tokens/**/*.json" means "every .json file
  // inside tokens/, at any depth". Today that is only tokens/tokens.json, but
  // any token files added later are picked up automatically.
  source: ['tokens/**/*.json'],

  // A "hook" is custom behaviour we plug into the build. Here we define our
  // own file header: the comment block printed at the top of every generated
  // file. It has no timestamp, so rebuilding does not create noisy diffs.
  hooks: {
    fileHeaders: {
      'knowunity/do-not-edit': () => [
        'THIS FILE IS GENERATED by Style Dictionary. DO NOT EDIT BY HAND.',
        'Your changes will be overwritten the next time the tokens are built.',
        'Edit the source tokens in tokens/ and run `npm run tokens` to regenerate.',
      ],
    },
  },

  // A "platform" is one output target. We have exactly one, named "css".
  platforms: {
    css: {
      // A transform group is a bundle of rules that convert token names and
      // values into one language's conventions. The built-in "css" group
      // turns each token's full path into a kebab-case name
      // (color.violet.500 -> --color-violet-500) and formats values for CSS.
      transformGroup: 'css',

      // The folder the generated files are written into.
      buildPath: 'build/css/',

      files: [
        {
          // Produces build/css/tokens.css.
          destination: 'tokens.css',

          // "css/variables" wraps every token in a :root { ... } block as CSS
          // custom properties (the --name: value; lines).
          format: 'css/variables',

          options: {
            // Use the custom header defined above.
            fileHeader: 'knowunity/do-not-edit',

            // Keep the links between tokens. A semantic token like
            // background.page points at color.navy.950; with this on, the
            // output is var(--color-navy-950) rather than a duplicated hex,
            // so the relationship stays in one place.
            outputReferences: true,
          },
        },
      ],
    },
  },
};
