// Style Dictionary configuration for knowunity-app.
//
// The SOURCE tokens are the single source of truth and live in the sibling
// design workspace: ../knowunity-sprint/tokens/. Figma reads that same file.
// This build turns those tokens into CSS variables the app can use.
//
// The generated file (styles/tokens.css) is committed, so the app builds on a
// fresh clone. Regenerating it requires the knowunity-sprint folder to sit
// next to this one (it does, inside Knowunity/).
//
// Build it with:  npm run tokens

export default {
  // Read the shared tokens from the sibling design workspace. "**/*.json"
  // means "every .json file inside that folder, at any depth".
  source: ['../knowunity-sprint/tokens/**/*.json'],

  // A "hook" is custom behaviour we plug into the build. This one defines the
  // comment block printed at the top of the generated file. No timestamp, so
  // rebuilding does not create noisy diffs.
  hooks: {
    fileHeaders: {
      'knowunity/do-not-edit': () => [
        'THIS FILE IS GENERATED by Style Dictionary. DO NOT EDIT BY HAND.',
        'Your changes will be overwritten the next time the tokens are built.',
        'Edit the source tokens in ../knowunity-sprint/tokens/tokens.json',
        'and run `npm run tokens` to regenerate.',
      ],
    },
  },

  // A "platform" is one output target. We have one, named "css".
  platforms: {
    css: {
      // The built-in "css" group turns each token's full path into a
      // kebab-case name (color.violet.500 -> --color-violet-500) and formats
      // values for CSS.
      transformGroup: 'css',

      // Write into styles/ (tracked). The app ignores /build, so we avoid it.
      buildPath: 'styles/',

      files: [
        {
          // Produces styles/tokens.css.
          destination: 'tokens.css',

          // Wrap every token in a :root { ... } block as CSS custom properties.
          format: 'css/variables',

          options: {
            fileHeader: 'knowunity/do-not-edit',

            // Keep the links between tokens: a semantic token like
            // background.page outputs var(--color-navy-950) rather than a
            // duplicated hex, so the relationship stays in one place.
            outputReferences: true,
          },
        },
      ],
    },
  },
};
